require 'saml/identity_provider'
require 'saml/metadata/sso_descriptor_type'
require 'saml/metadata/idp_sso_descriptor'
require 'saml/service_provider'
require 'saml/session'
require 'saml/session_register'
require 'saml/user'
