require 'saml/bindings'
require 'saml/bindings/http_post'
require 'saml/bindings/http_redirect'

require 'saml/core/assertion'
require 'saml/core/attribute'
require 'saml/core/attribute_statement'
require 'saml/core/document'
require 'saml/core/request_abstract'
require 'saml/core/logout_request'
require 'saml/core/authn_request'
require 'saml/core/status_response'
require 'saml/core/status'
require 'saml/core/response'
require 'saml/core/xml_namespaces'

require 'saml/metadata/document'
require 'saml/metadata/entities_descriptor'
require 'saml/metadata/entity_descriptor'
require 'saml/metadata/endpoint'
require 'saml/metadata/indexed_endpoint'
require 'saml/metadata/sso_descriptor'
require 'saml/metadata/idp_sso_descriptor'
require 'saml/metadata/sp_sso_descriptor'
require 'saml/metadata/xml_namespaces'
